### ISSUE TITLE
char_embeddings

### ISSUE THREAD

**Issue by adnankhawaja** [Darg-Iztech/Gender_Classification#1]
Hi,

Sorry for a very naive request. I am very new to the tf/ w2v actually. Could you please guide me where i can download the file: "char_embeddings.27B.25d.txt". I am able to download the file "glove.twitter.27B.50d.txt" but not the char_embeddings one.

**Comment by polatbilek** [comment]
Hi,

The sample "char_embeddings" that we have used in the article is added on repo now.

The har embeddings are learned on the fly, the file stands for only vocabulary actually. 

           

           with tf.name_scope("embedding"):

                 W = tf.Variable(tf.random_uniform([vocab_size, embedding_size], -1.0, 1.0), name="W")

                 self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)

                 self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)

sample of code above from text_cnn.py is responsible for training the embeddings. So all in all, it doesn't matter what you used as file, if you feed vocabulary file like ours, that would be okay.

Thanks for notifying that. Have a nice day.

**Comment by adnankhawaja** [comment]
Thankyou for the embeddings file. I do have some basic errors while running the code:
I have attached the error image. 
return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.


![error1](https://user-images.githubusercontent.com/39548061/43379899-5e282458-9401-11e8-8a9e-0ffb96978c89.jpg)


I suppose the following changes should have no impact on the above error.
line 91, in preprocessing.py
    words = line.strip().split(b':::')  ---to-->  words = line.strip().split(':::') 
to avoid the TypeError: must be str or None, not bytes

**Comment by polatbilek** [comment]
Could you please give us more info about your inputs and environment so that we can reproduce the error? We haven't faced with this error so far.

**Comment by adnankhawaja** [comment]
I am using the PAN-18 English text dataset.  I am running code using Python 3.5 on windows (64bit) environment.

**Comment by ErhanSezerer** [comment]
We have just updated the codes. We believe that it will solve your issue. Can you try the newest version and notify us whether it worked for you or not?

**Comment by adnankhawaja** [comment]
Thank you. It is working fine now.
